[package]
name = "memory-mirror"
version = "0.2.0"
edition = "2021"

[dependencies]
sysinfo = "0.28"
indicatif = "0.17.3"
#pe-util = { version = "0.1.0" , git = "https://github.com/Nordgaren/pe-util.git" }
pe-util = { version = "0.1.0" , path = "../pe-util" }
